# Generated by Django 2.1.4 on 2018-12-15 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('util', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('puntos', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_dir', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Calle')),
                ('numero_dir', models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Calle')),
                ('nombre', models.CharField(max_length=250)),
                ('cuit', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CUIT')),
                ('telefono', models.BigIntegerField(blank=True, null=True, verbose_name='Número de Teléfono')),
                ('puntos', models.PositiveIntegerField(blank=True, default=0)),
                ('historico_puntos', models.PositiveIntegerField(blank=True, default=0)),
                ('localidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Localidad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='servicio',
            field=models.ManyToManyField(to='proveedor.Servicio'),
        ),
        migrations.AddField(
            model_name='beneficio',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedor.Servicio'),
        ),
    ]
