# Generated by Django 2.1.4 on 2018-12-16 12:41

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0003_proveedor_ubicacion'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='proveedor',
            managers=[
                ('conjunto', django.db.models.manager.Manager()),
            ],
        ),
    ]
