# Generated by Django 2.1.4 on 2018-12-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0004_auto_20181216_0941'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='proveedor',
            managers=[
            ],
        ),
    ]
