# Generated by Django 2.1.4 on 2018-12-16 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0002_auto_20181215_1838'),
        ('util', '0001_initial'),
        ('asistencia', '0004_auto_20181215_1355'),
        ('proveedor', '0005_auto_20181216_0944'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='ProveedorServicio',
        ),
    ]
