"""
Django settings for turismo project.

Generated by 'django-admin startproject' using Django 2.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'rtsgfn61-pc050hzz3lg%ybmuejx*+(+onqvif##=ljm@6*zzp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.gis',
    'django.contrib.auth',
    'django.contrib.sites',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'pwa',
    'django_extensions',
    'snowpenguin.django.recaptcha2',
    'bootstrap4',
    'mapwidgets',

    'asistencia',
    'capacitacion',
    'core',
    'proveedor',
    'servicio',
    #'user',
    'pagina',
    'util',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'turismo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
            ],
        },
    },
]

WSGI_APPLICATION = 'turismo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'turismo',
        'USER': 'turismo',
        'PASSWORD': 'qazwsx_turismo_plmokn',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization

LANGUAGE_CODE = 'es_ES.UTF-8'
TIME_ZONE = 'America/Argentina/Catamarca'
USE_I18N = True
USE_L10N = True
USE_TZ = True


# Static files

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(os.path.abspath(BASE_DIR), 'static')
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, "assets"),
)


MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(os.path.abspath(BASE_DIR), 'media')

# SITE ID
SITE_ID = 1


# Jet Settings
JET_INDEX_DASHBOARD = 'core.dashboard.CustomDashboard'
JET_SIDE_MENU_COMPACT = True
JET_DEFAULT_THEME = 'light-gray'

# PWA Settings
# PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'serviceworker/', 'serviceworker.js')
# PWA_APP_NAME = ''
# PWA_APP_DESCRIPTION = ""
# PWA_APP_THEME_COLOR = '#004a95'
# PWA_APP_DISPLAY = 'standalone'
# PWA_APP_START_URL = '/'
# PWA_APP_ICONS = [
#     {
#         'src': '/static/images/',
#         'sizes': '192x192'
#     },
#     {
#         'src': '/static/images/',
#         'sizes': '512x512'
#     }
# ]


# User Custom
#AUTH_USER_MODEL = 'user.User'

ALLOWED_HOSTS = ['*']
GOOGLEAPIKEY = 'AIzaSyARCObAv-lfCntgLLGN9y36PsyMD1JF7zo'

# PWA Settings
PWA_SERVICE_WORKER_PATH = os.path.join(BASE_DIR, 'static/serviceworker', 'serviceworker.js')
PWA_APP_NAME = 'Mejoremos y Punto'
PWA_APP_DESCRIPTION = ""
PWA_APP_THEME_COLOR = '#004a95'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_START_URL = '/'
PWA_APP_ICONS = [
    {
        'src': '/static/img/cerebrito.jpg',
        'sizes': '192x192'
    },
    {
        'src': '/static/img/cerebrito.jpg',
        'sizes': '512x512'
    }
]