# Generated by Django 2.1.4 on 2018-12-15 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capacitacion',
            options={'verbose_name_plural': 'Capacitaciones'},
        ),
    ]
