# Generated by Django 2.1.4 on 2018-12-15 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('util', '0001_initial'),
        ('capacitacion', '0002_auto_20181215_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitacion',
            name='localidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='util.Localidad'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='nombre_dir',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre de Calle'),
        ),
        migrations.AddField(
            model_name='capacitacion',
            name='numero_dir',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de Calle'),
        ),
    ]
