# Generated by Django 2.1.4 on 2018-12-15 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('capacitacion', '0002_auto_20181215_1226'),
        ('asistencia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='capacitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='capacitacion.Capacitacion'),
            preserve_default=False,
        ),
    ]
